<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>marc_app</RootNamespace>
  </PropertyGroup>

    <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <RootNamespace>marc-app</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>marc-marc_app</PackageId>
    <Version>1.0</Version>
    <Authors>marc</Authors>
    <Company>marct22</Company>

  </PropertyGroup>


</Project>
